version: '3'

volumes:
  db:
    driver: local
  dbc:
    driver: local

services:
  php:
    container_name: anidb
    restart: unless-stopped
    build:
      context: ./docker
      dockerfile: php.dockerfile
      args:
        - PHP_VERSION=8.3.9
        - ALPINE_VERSION=3.20
        - COMPOSER_VERSION=2.7.7
    volumes:
      - ./:/var/www
    expose:
      - "9000"
    working_dir: /var/www
    tty: true

  nginx:
    container_name: anidb-nginx
    restart: unless-stopped
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
      args:
        - NGINX_VERSION=1.26
        - PHP_UPSTREAM_CONTAINER=php
        - PHP_UPSTREAM_PORT=9000
    volumes:
      - ./:/var/www
      - ./docker/logs/:/var/log/nginx
      - ./docker/sites/:/etc/nginx/sites-available
    ports:
      - "${APP_PORT:-80}:80"
    expose:
      - "${APP_PORT:-80}"
    depends_on:
      - php

  db:
    container_name: anidb-pgsql
    image: postgres:16.3-alpine3.20
    restart: unless-stopped
    tty: true
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_DATABASE:-anidb}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - db:/var/lib/postgresql/data

  dbc:
    container_name: anidb-cockroach
    image: cockroachdb/cockroach:v23.1.24
    restart: unless-stopped
    ports:
     - "${DBC_PORT:-26257}:26257"
     - "${DBC_ADMIN_PORT:-8080}:8080"
    command: start-single-node --insecure
    volumes:
      - dbc:/cockroach/cockroach-data"
