volumes:
  db:
    driver: local
  caddy_data:
  caddy_config:

services:
  php:
    container_name: anidb
    restart: unless-stopped
    build:
      context: ./docker
      dockerfile: php.dockerfile
      args:
        - PHP_VERSION=8.4.5
        - ALPINE_VERSION=3.21
        - COMPOSER_VERSION=2.8.8
    volumes:
      - ./:/srv
    expose:
      - "9000"
    working_dir: /srv
    tty: true

  caddy:
    container_name: anidb-caddy
    image: caddy:2.9.1-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/caddyfile:/etc/caddy/Caddyfile
      - ./:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - php

  db:
    container_name: anidb-pgsql
    image: postgres:17.4-alpine3.21
    restart: unless-stopped
    tty: true
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_DATABASE:-anidb}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - db:/var/lib/postgresql/data
    command: -c shared_buffers=512MB
