version: '3'

volumes:
  db:
    driver: local

services:
  php:
    container_name: anidb
    restart: unless-stopped
    build:
      context: ./docker
      dockerfile: php.dockerfile
      args:
        - PHP_VERSION=8.0
        - COMPOSER_VERSION=2.5.1
    volumes:
      - ./:/var/www
    expose:
      - "9000"
    working_dir: /var/www
    tty: true

  nginx:
    container_name: anidb-nginx
    restart: unless-stopped
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
      args:
        - NGINX_VERSION=1.23.2
        - PHP_UPSTREAM_CONTAINER=php
        - PHP_UPSTREAM_PORT=9000
    volumes:
      - ./:/var/www
      - ./docker/logs/:/var/log/nginx
      - ./docker/sites/:/etc/nginx/sites-available
    ports:
      - "${APP_PORT:-80}:80"
    expose:
      - "${APP_PORT:-80}"
    depends_on:
      - php

  db:
    container_name: anidb-pgsql
    image: postgres:13.7-alpine3.16
    restart: unless-stopped
    tty: true
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_DATABASE:-anidb}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - db:/var/lib/postgresql/data
